---
title: "CO2 and CH4"
output:
  html_document:
    df_print: paged
---

Caricamento dei dati e delle librerie

```{r}
library(ggplot2)
library(zoo)
edc.co2.2008_EXTRACTED <- read.csv("Data/edc-co2-2008_EXTRACTED.txt", sep="")
edc.ch4.2008_EXTRACTED<- read.csv("Data/edc-ch4-2008_EXTRACTED.txt", sep="")
temperature<- read.csv("Data/temperature_EXTRACTED.txt", sep="")

```

Creazione di un dataframe con dei nomi diversi per le colonne

```{r}
CO2 <- data.frame(edc.co2.2008_EXTRACTED$Age, edc.co2.2008_EXTRACTED$CO2)
CH4 <- data.frame(edc.ch4.2008_EXTRACTED$GasAge, edc.ch4.2008_EXTRACTED$CH4mean)
Temp <- data.frame(temperature$Age , temperature$Temperature)
colnames(CO2)<- c("Age","CO2")
colnames(CH4)<- c("Age","CH4")
colnames(Temp)<- c("Age","Temperature")
```

Creazione del grafico

```{r}
ggplot(data = CO2, aes(x = Age, y = CO2)) + geom_line(colour='red') + geom_point(colour='red')  + 
scale_y_continuous(name ="CO2 (ppm)") +  scale_x_continuous(name ="Age (yrBP)") + theme_bw()

```
```{r}
ggplot(data = CH4, aes(x = Age, y = CH4)) + geom_line(colour='blue') + geom_point(colour='blue')  + 
scale_y_continuous(name ="CH4 (ppb)") +  scale_x_continuous(name ="Age (yrBP)") + theme_bw()

```


Calcolo della media e della devizione standard. La concentrazione attuale di CO2 è di 412 ppm , mentre di CH4 1879 ppb (NOAA)

```{r}

CO2_mean <- mean(CO2$CO2)
Co2_sd <- sd(CO2$CO2)
print(c(CO2_mean,Co2_sd))
```

```{r}

CH4_mean <- mean(CH4$CH4)
CH4_sd <- sd(CH4$CH4)
print(c(CH4_mean ,CH4_sd ))
```


```{r}
CO2$CO2_scaled <- scale(CO2$CO2 , scale = TRUE)
CH4$CH4_scaled <- scale(CH4$CH4 , scale = TRUE)
Temp$Temperature_scaled<- scale(Temp$Temperature , scale = TRUE)
```


```{r}
ggplot(data = CO2, aes(x = Age, y = CO2_scaled)) + geom_line(colour='red') + geom_point(colour='red')  + 
scale_y_continuous(name ="CO2 (ppm)") +  scale_x_continuous(name ="Age (yrBP)") + theme_bw()

```



```{r}
ggplot(data = CH4, aes(x = Age, y = CH4_scaled)) + geom_line(colour='blue') + geom_point(colour='blue')  + 
scale_y_continuous(name ="CH4 (ppb)") +  scale_x_continuous(name ="Age (yrBP)") + theme_bw()

```


```{r}
ggplot(data = Temp, aes(x = Age, y = Temperature)) + geom_line(colour='orange') + geom_point(colour='orange')  + 
scale_y_continuous(name ="Delta T (C)") +  scale_x_continuous(name ="Age (yrBP)") + theme_bw()

```


```{r}

ggplot(data = CH4, aes(x = Age, y = CH4_scaled)) + geom_line(colour='blue') + geom_point(colour='blue')  + 
scale_y_continuous(name ="CH4 CO2 and T arb. units ") +  scale_x_continuous(name ="Age (yrBP)") + geom_line(data = CO2, aes(x = Age, y = CO2_scaled),colour='red')+ geom_point(data = CO2, aes(x = Age, y = CO2_scaled),colour='red')+ geom_line(data = Temp, aes(x = Age, y = Temperature_scaled),colour='orange')+ geom_point(data = Temp, aes(x = Age, y = Temperature_scaled),colour='orange')+theme_bw()

```

Ora analizziamo la situazione attuale 


```{r}
actual_CO2 <- read.csv("Data/ACTUALCO2_extracted.txt", sep="")
actual_temperature <- read.csv("~/GitHub/Climate_Change_tutorial/Data/data.csv")
colnames(actual_CO2)<- c("Age","CO2")
colnames(actual_temperature)<- c("Age","Temperature")

```

```{r}
actual_CO2$CO2_scaled <- scale(actual_CO2$CO2 , scale = TRUE)
actual_temperature$Temperature_scaled <- scale(actual_temperature$Temperature , scale = TRUE)
```

```{r}

ggplot(data = actual_CO2, aes(x = Age, y = CO2_scaled)) + geom_line(colour='blue') + geom_point(colour='blue')  + 
scale_y_continuous(name ="T and CO2 arb. units ") +  scale_x_continuous(name ="Age (yrBP)")+ geom_line(data = actual_temperature, aes(x = Age, y = Temperature_scaled),colour='orange')+ geom_point(data = actual_temperature, aes(x = Age, y = Temperature_scaled),colour='orange')+theme_bw()

```


